name: Trigger auto deployment for virtual

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/virtual-AutoDeployTrigger-f8c46c84-b15a-447d-85ba-26e50f16df9d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.VIRTUAL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VIRTUAL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VIRTUAL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.VIRTUAL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VIRTUAL_REGISTRY_PASSWORD }}
          containerAppName: virtual
          resourceGroup: catv2ton-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


